name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
include-labels:
  - 'feature'
  - 'enhancement'
  - 'test'
  - 'fix'
  - 'bugfix'
  - 'bug'
  - 'documentation'
categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Enhancement'
    labels: 
      - 'enhancement'
      - 'documentation'
      - 'test'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES

  $CONTRIBUTORS
