# This is a basic workflow to help you get started with Actions

name: Create Issue in Oden

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [ opened ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  export:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a set of commands using the runners shell
    - name: Create an issue in Oden.
      run: |
        Install-Module -Name EasitGoWebservice
        Import-Module EasitGoWebservice
        Import-GORequestItem -url ${{ matrix.node_version }} -apikey ${{ matrix.node_version }} -ihi ${{ matrix.node_version }} -Description "Updating description for request 156" -Subject ""
      shell: pwsh
