name: Test tests with Pester

on:
  pull_request:
    branches: [ "release3" ]
    paths:
    - 'tests/v3/function/**'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Invoke Pester
      shell: pwsh
      run: Invoke-Pester -Path .\tests\v3\function\
