name: Test tests with Pester

on:
  pull_request:
    paths:
    - 'tests/**'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Pester
      shell: pwsh
      run: Update-Module Pester -Force
    - name: Invoke Pester
      shell: pwsh
      run: Invoke-Pester
