name: Check source compliance with PowerShell Script Analyzer

on:
  pull_request:
    branches:
      - 'release3' # will later be changed to run for all branches
    paths:
    - 'source/v3/**'
  workflow_dispatch:

jobs:
  test:
    name: Run PSSA
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: lint
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        failOnErrors: true
        failOnWarnings: false
        failOnInfos: false
        settingsPath: ./.github/PSScriptAnalyzerSettings.psd1
