name: Publish to PS Gallery

on:
  push:
    branches:
      - master
    tags:        
      - v1.*

jobs:
  lint:
    name: Run psscriptanalyzer
    runs-on: ubuntu-latest
    steps:
    - uses: devblackops/github-action-psscriptanalyzer@master

  test_individual_functions:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester
      shell: pwsh
      run: Install-Module Pester -Force
    - name: Invoke Pester
      shell: pwsh
      run: Invoke-Pester -EnableExit

#  build:
#    needs: test_individual_functions
#    runs-on: windows-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: Run build script
#      shell: pwsh
#      run: .\build\build.ps1

#  test_module:
#    needs: build
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest, windows-latest, macOS-latest]

#  publish:
#    needs: [test_module, build]