name: Release Notes

on:
  push:
    branches: [ "release3" ]
    paths-ignore:
    - '.github/**'
    - 'workflows/**'
  workflow_dispatch:

jobs:
  update_release_draft:
    name: update_release_draft
    runs-on: ubuntu-latest
    steps:
      - name: generate_release_draft

        uses: release-drafter/release-drafter@v5
        with:

          config-name: release-drafter-template-v3.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}