name: Push and PR check

on:
  push:
    paths:
    - 'functions/*.ps1'
  pull_request:
    paths:
    - 'functions/*.ps1'

jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
    - uses: devblackops/github-action-psscriptanalyzer@master

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester
      shell: pwsh
      run: Install-Module Pester -Force
    - name: Invoke Pester
      shell: pwsh
      run: Invoke-Pester -EnableExit
